export const serverImageMap: {[key: string]: string} = {
    '리부트': '/icons/server/reboot.webp',
    '리부트2': '/icons/server/reboot.webp',
    '에오스': '/icons/server/eos.png',
    '스카니아': '/icons/server/scania.png',
    '루나': '/icons/server/luna.png',
    '엘리시움': '/icons/server/elysium.png',
    '크로아': '/icons/server/croa.png',
    '베라': '/icons/server/bera.png',
    '레드': '/icons/server/red.png',
    '오로라': '/icons/server/aurora.png',
    '이노시스': '/icons/server/enosis.png',
    '아케인': '/icons/server/arcane.png',
    '노바': '/icons/server/nova.png',
    '버닝': '/icons/server/burning.png',
    '버닝1': '/icons/server/burning.png',
    '버닝2': '/icons/server/burning.png',
    '버닝3': '/icons/server/burning.png',
    '챌린저스1': '/icons/server/challengers.png',
    '챌린저스2': '/icons/server/challengers.png',
    '챌린저스3': '/icons/server/challengers.png',
    '챌린저스4': '/icons/server/challengers.png',
    // '예티X핑크빈': '/icons/server/YETIxPINKBEAN.png',
};